spring.application.name=desafio

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.desafio.fcamara.desafio=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true

server.port=8081